function [A,b] = Eoms(IM,Il,M,R,T,g,l,phi,r,t)
%EOMS
%    [A,B] = EOMS(IM,IL,M,R,T,G,L,PHI,R,T)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    07-Dec-2015 12:33:52

t2 = sin(phi);
t3 = cos(phi);
A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3,-t2,r,-t3,R,t2,t3,0.0,-t2,0.0,0.0,0.0,0.0,1.0,R],[5,5]);
if nargout > 1
    t4 = psi(2,t);
    t5 = 1.0./pi;
    b = [l.*r.*t4.*t5.*(1.0./2.0);g.*l;-T+Il.*t4;M.*r.*t4.*t5.*(1.0./2.0);(IM.*r.*t4.*t5.*(-1.0./2.0))./R];
end
